### ISSUE TITLE
E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by Krishnarohith10** [Krishnarohith10/CIFAR-10-CNN#1]
**System information**
**OS Platform and Distribution**: Windows 10 Version 1909
**TensorFlow GPU version**: 2.0.0
**Python version**: 3.6.10
**CUDA version**: 10.0.130
**cuDNN version**: 7.6.5
**Nvidia Graphics version**: 441.87
**GPU model and memory**:
Intel(R) UHD Graphics 630, Shared GPU Memory: 15.9GB
Nvidia GeForce GTX 1660 Ti, Dedicated GPU Memory: 6GB
**Memory(RAM)**: 32GB (31.8GB) Available: 25.6GB

I get this error message when I run  a deep learning code And according to official tensorflow.org/install/gpu website my system does support as per that website.

This is my GPU information:
![1](https://user-images.githubusercontent.com/44919399/72126933-f01f1780-3393-11ea-9131-62ee503eaff3.jpg)

Here's the error:
![2](https://user-images.githubusercontent.com/44919399/72126970-0d53e600-3394-11ea-8735-7c04742e2313.jpg)

Thank You for Your Contribution

**Comment by Krishnarohith10** [comment]
This issuse is no longer a issue. I had it done by updating few packages and it solved my issue.
Tensorflow GPU version: 2.1.0
Nvidia CUDA version: 10.1
Nvidia cuDNN version: 7.6.5

This is it. Hope it solves for You.
